name = "sirius-lepactedesombres"
main = "_worker.js"
compatibility_date = "2026-08-25"
workers_dev = false
preview_urls = false
keep_vars = true

[[routes]]
pattern = "sirius-lepactedesombres.nyxia.top"
zone_name = "nyxia.top"
custom_domain = true

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = true

[[kv_namespaces]]
binding = "CASHFLOW_KV"
id = "106db6da016d49d2b480452f19bad695"

[[d1_databases]]
binding = "DB"
database_name = "nyxia-cercles-db"
database_id = "a21fd813-06fa-41f1-b744-07bf1c5c7951"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "univers-livres"

[vars]
SITE_URL = "https://sirius-lepactedesombres.nyxia.top/"
GAME_ID = "ee2eaf9b-4708-4891-8e0d-f1800cdabe76"
PORTAIL = "sirius-lepactedesombres"
[[kv_namespaces]]
binding = "SPIRITUEL_KV"
id = "3e730b1c49f94e32a97cceff3b60a773"

